//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public string rut { get; set; }
        public string username { get; set; }
        public int edad { get; set; }
        public string sexo { get; set; }
        public bool exp_prev { get; set; }
        public string computador { get; set; }
    }
}
